dist: xenial
sudo: required

matrix:
  include:
    - language: go
      go: "1.12.x"
      install:
      - export GOPATH=/home/travis/gopath
      - export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
      script:
      - make build
      - go test ./pkg/istio/objects -v
