[[constraint]]
  name = "k8s.io/client-go"
  version ="v12.0.0"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.15"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.15"
