# Default values for amc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: servicemesh-amc
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

avi:
  controller_username: "admin"
  controller_password: "admin"
  controller_ip: "0.0.0.0:9443"
  controller_version: "18.2.5"
  cloud_name: "ISTIO_DEMO"
  network_name: "northsouthnetwork"
  network_cidr: "192.168.2.0/24"
  network_static_range_start: "192.168.2.101"
  network_static_range_end: "192.168.2.150"
  ipam_subdomain: "avi.dns.com"
  k8s_master_node: "x"
  k8s_service_token: "y"

istio:
  enabled: "True"
  mcp_url: "mcp://istio-galley.istio-system.svc:9901"

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
