---
# tasks file for 01_cloudformation
- debug: msg="aws access key-- {{ aws_access_key }}"
- name: Create cloud
  cloudformation:
    stack_name: "AviServiceMesh{{ ansible_date_time.iso8601_basic }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    template_url: "https://s3-us-west-2.amazonaws.com/aviservicemesh/kubernetes-cluster-with-new-vpc.template"
    state: present
    region: "{{ ec2_region }}"
    template_parameters:
      KeyName: "{{ ec2_key_name }}"
      AvailabilityZone: "us-west-2b"
      R53HostedZone: "{{ r53_hosted_zone }}"
      AdminIngressLocation: "0.0.0.0/0"